# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_common/coordinator/coordinator_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2proto_common/coordinator/coordinator_service.proto\x12\x06tensor\"\x07\n\x05\x45mpty\"\r\n\x0bLossMessage2q\n\x12\x43oordinatorService\x12*\n\nbatch_done\x12\r.tensor.Empty\x1a\r.tensor.Empty\x12/\n\tshow_loss\x12\x13.tensor.LossMessage\x1a\r.tensor.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_common.coordinator.coordinator_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=62
  _globals['_EMPTY']._serialized_end=69
  _globals['_LOSSMESSAGE']._serialized_start=71
  _globals['_LOSSMESSAGE']._serialized_end=84
  _globals['_COORDINATORSERVICE']._serialized_start=86
  _globals['_COORDINATORSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
