# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from torchslicer.transport.grpc.coordinator import coordinator_service_pb2 as torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in torchslicer/transport/grpc/coordinator/coordinator_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.batch_done = channel.unary_unary(
                '/torchslicer.coordinator.CoordinatorService/batch_done',
                request_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.BatchDoneRequest.SerializeToString,
                response_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.FromString,
                _registered_method=True)
        self.report_metrics = channel.unary_unary(
                '/torchslicer.coordinator.CoordinatorService/report_metrics',
                request_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.MetricsMessage.SerializeToString,
                response_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.FromString,
                _registered_method=True)
        self.register = channel.unary_unary(
                '/torchslicer.coordinator.CoordinatorService/register',
                request_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.report_worker_error = channel.unary_unary(
                '/torchslicer.coordinator.CoordinatorService/report_worker_error',
                request_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.WorkerError.SerializeToString,
                response_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def batch_done(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def report_metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def report_worker_error(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'batch_done': grpc.unary_unary_rpc_method_handler(
                    servicer.batch_done,
                    request_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.BatchDoneRequest.FromString,
                    response_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.SerializeToString,
            ),
            'report_metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.report_metrics,
                    request_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.MetricsMessage.FromString,
                    response_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.SerializeToString,
            ),
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.RegisterRequest.FromString,
                    response_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.RegisterResponse.SerializeToString,
            ),
            'report_worker_error': grpc.unary_unary_rpc_method_handler(
                    servicer.report_worker_error,
                    request_deserializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.WorkerError.FromString,
                    response_serializer=torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'torchslicer.coordinator.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('torchslicer.coordinator.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def batch_done(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/torchslicer.coordinator.CoordinatorService/batch_done',
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.BatchDoneRequest.SerializeToString,
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def report_metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/torchslicer.coordinator.CoordinatorService/report_metrics',
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.MetricsMessage.SerializeToString,
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/torchslicer.coordinator.CoordinatorService/register',
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.RegisterRequest.SerializeToString,
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def report_worker_error(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/torchslicer.coordinator.CoordinatorService/report_worker_error',
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.WorkerError.SerializeToString,
            torchslicer_dot_transport_dot_grpc_dot_coordinator_dot_coordinator__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
