
FROM marcog94/torchslicer:base-grpc-cpu



RUN mkdir /train
COPY examples/train/${PARADIGM}/GRPC/worker/ /train/${PARADIGM}/GRPC/worker/
# COPY examples/train/${PARADIGM}/REST/worker/ /train/${PARADIGM}/REST/worker/
COPY lib/torchslicer/ /usr/local/bin/torchslicer/
RUN chmod 777 -R /usr/local/bin/torchslicer/*    


RUN python3 -m pip  install /usr/local/bin/torchslicer

WORKDIR /train



# Install PyTorch and its dependencies
RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu

# Set the default command to execute when the container starts
# CMD ["python3","/train/main.py"]

#RUN python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. "./${PARADIGM}/${PROTOCOL}/worker/worker_service.proto"
RUN python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. "./${PARADIGM}/${PROTOCOL}/proto_common/worker/worker_service.proto"


CMD python3 "/train/${PARADIGM}/${PROTOCOL}/worker/main.py"
