[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "torchslicer"
version = "0.2.0"
description = "Split learning framework for PyTorch."
authors = [{name = "Marco Garofalo", email = "garofalomarco58@gmail.com"}]
requires-python = ">=3.10"
dependencies = ["numpy"]

[tool.setuptools.packages.find]
where = ["."]
