# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tensor_service_pb2 as tensor__service__pb2


class TensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init = channel.unary_unary(
                '/tensor.TensorService/init',
                request_serializer=tensor__service__pb2.Config.SerializeToString,
                response_deserializer=tensor__service__pb2.LogMessage.FromString,
                )
        self.set_label = channel.unary_unary(
                '/tensor.TensorService/set_label',
                request_serializer=tensor__service__pb2.Tensor.SerializeToString,
                response_deserializer=tensor__service__pb2.LogMessage.FromString,
                )
        self.forward = channel.unary_unary(
                '/tensor.TensorService/forward',
                request_serializer=tensor__service__pb2.ForwardMessage.SerializeToString,
                response_deserializer=tensor__service__pb2.Empty.FromString,
                )
        self.backward = channel.unary_unary(
                '/tensor.TensorService/backward',
                request_serializer=tensor__service__pb2.BackwardMessage.SerializeToString,
                response_deserializer=tensor__service__pb2.Empty.FromString,
                )
        self.batch_done = channel.unary_unary(
                '/tensor.TensorService/batch_done',
                request_serializer=tensor__service__pb2.Empty.SerializeToString,
                response_deserializer=tensor__service__pb2.Empty.FromString,
                )
        self.show_loss = channel.unary_unary(
                '/tensor.TensorService/show_loss',
                request_serializer=tensor__service__pb2.LossMessage.SerializeToString,
                response_deserializer=tensor__service__pb2.Empty.FromString,
                )


class TensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_label(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def backward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def batch_done(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def show_loss(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init': grpc.unary_unary_rpc_method_handler(
                    servicer.init,
                    request_deserializer=tensor__service__pb2.Config.FromString,
                    response_serializer=tensor__service__pb2.LogMessage.SerializeToString,
            ),
            'set_label': grpc.unary_unary_rpc_method_handler(
                    servicer.set_label,
                    request_deserializer=tensor__service__pb2.Tensor.FromString,
                    response_serializer=tensor__service__pb2.LogMessage.SerializeToString,
            ),
            'forward': grpc.unary_unary_rpc_method_handler(
                    servicer.forward,
                    request_deserializer=tensor__service__pb2.ForwardMessage.FromString,
                    response_serializer=tensor__service__pb2.Empty.SerializeToString,
            ),
            'backward': grpc.unary_unary_rpc_method_handler(
                    servicer.backward,
                    request_deserializer=tensor__service__pb2.BackwardMessage.FromString,
                    response_serializer=tensor__service__pb2.Empty.SerializeToString,
            ),
            'batch_done': grpc.unary_unary_rpc_method_handler(
                    servicer.batch_done,
                    request_deserializer=tensor__service__pb2.Empty.FromString,
                    response_serializer=tensor__service__pb2.Empty.SerializeToString,
            ),
            'show_loss': grpc.unary_unary_rpc_method_handler(
                    servicer.show_loss,
                    request_deserializer=tensor__service__pb2.LossMessage.FromString,
                    response_serializer=tensor__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensor.TensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensor.TensorService/init',
            tensor__service__pb2.Config.SerializeToString,
            tensor__service__pb2.LogMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_label(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensor.TensorService/set_label',
            tensor__service__pb2.Tensor.SerializeToString,
            tensor__service__pb2.LogMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensor.TensorService/forward',
            tensor__service__pb2.ForwardMessage.SerializeToString,
            tensor__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def backward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensor.TensorService/backward',
            tensor__service__pb2.BackwardMessage.SerializeToString,
            tensor__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def batch_done(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensor.TensorService/batch_done',
            tensor__service__pb2.Empty.SerializeToString,
            tensor__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def show_loss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensor.TensorService/show_loss',
            tensor__service__pb2.LossMessage.SerializeToString,
            tensor__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
