# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from worker import worker_service_pb2 as worker_dot_worker__service__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in worker/worker_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init = channel.unary_unary(
                '/tensor.WorkerService/init',
                request_serializer=worker_dot_worker__service__pb2.Config.SerializeToString,
                response_deserializer=worker_dot_worker__service__pb2.LogMessage.FromString,
                _registered_method=True)
        self.set_label = channel.unary_unary(
                '/tensor.WorkerService/set_label',
                request_serializer=worker_dot_worker__service__pb2.Tensor.SerializeToString,
                response_deserializer=worker_dot_worker__service__pb2.LogMessage.FromString,
                _registered_method=True)
        self.forward = channel.unary_unary(
                '/tensor.WorkerService/forward',
                request_serializer=worker_dot_worker__service__pb2.ForwardMessage.SerializeToString,
                response_deserializer=worker_dot_worker__service__pb2.ForwardStatusMessage.FromString,
                _registered_method=True)
        self.backward = channel.unary_unary(
                '/tensor.WorkerService/backward',
                request_serializer=worker_dot_worker__service__pb2.BackwardMessage.SerializeToString,
                response_deserializer=worker_dot_worker__service__pb2.BackwardStatusMessage.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_label(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def backward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init': grpc.unary_unary_rpc_method_handler(
                    servicer.init,
                    request_deserializer=worker_dot_worker__service__pb2.Config.FromString,
                    response_serializer=worker_dot_worker__service__pb2.LogMessage.SerializeToString,
            ),
            'set_label': grpc.unary_unary_rpc_method_handler(
                    servicer.set_label,
                    request_deserializer=worker_dot_worker__service__pb2.Tensor.FromString,
                    response_serializer=worker_dot_worker__service__pb2.LogMessage.SerializeToString,
            ),
            'forward': grpc.unary_unary_rpc_method_handler(
                    servicer.forward,
                    request_deserializer=worker_dot_worker__service__pb2.ForwardMessage.FromString,
                    response_serializer=worker_dot_worker__service__pb2.ForwardStatusMessage.SerializeToString,
            ),
            'backward': grpc.unary_unary_rpc_method_handler(
                    servicer.backward,
                    request_deserializer=worker_dot_worker__service__pb2.BackwardMessage.FromString,
                    response_serializer=worker_dot_worker__service__pb2.BackwardStatusMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensor.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tensor.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tensor.WorkerService/init',
            worker_dot_worker__service__pb2.Config.SerializeToString,
            worker_dot_worker__service__pb2.LogMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_label(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tensor.WorkerService/set_label',
            worker_dot_worker__service__pb2.Tensor.SerializeToString,
            worker_dot_worker__service__pb2.LogMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tensor.WorkerService/forward',
            worker_dot_worker__service__pb2.ForwardMessage.SerializeToString,
            worker_dot_worker__service__pb2.ForwardStatusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def backward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tensor.WorkerService/backward',
            worker_dot_worker__service__pb2.BackwardMessage.SerializeToString,
            worker_dot_worker__service__pb2.BackwardStatusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
