# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker/worker_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bworker/worker_service.proto\x12\x06tensor\x1a\x1cgoogle/protobuf/struct.proto\"/\n\rTensorMessage\x12\x1e\n\x06tensor\x18\x01 \x01(\x0b\x32\x0e.tensor.Tensor\"\xc0\x02\n\x06\x43onfig\x12\'\n\x06layers\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\x12/\n\tcriterion\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x88\x01\x01\x12*\n\toptimizer\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x14\n\x07is_last\x18\x05 \x01(\x08H\x01\x88\x01\x01\x12\x17\n\nprev_layer\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x17\n\nnext_layer\x18\x07 \x01(\tH\x03\x88\x01\x01\x12\x1c\n\x0finit_state_dict\x18\x08 \x01(\x08H\x04\x88\x01\x01\x42\x0c\n\n_criterionB\n\n\x08_is_lastB\r\n\x0b_prev_layerB\r\n\x0b_next_layerB\x12\n\x10_init_state_dict\"\x16\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"]\n\x0e\x46orwardMessage\x12\x1d\n\x05input\x18\x01 \x01(\x0b\x32\x0e.tensor.Tensor\x12\"\n\x05label\x18\x02 \x01(\x0b\x32\x0e.tensor.TensorH\x00\x88\x01\x01\x42\x08\n\x06_label\"3\n\x0f\x42\x61\x63kwardMessage\x12 \n\x08gradient\x18\x01 \x01(\x0b\x32\x0e.tensor.Tensor\"@\n\nLogMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0f\n\x07ip_addr\x18\x03 \x01(\t\"X\n\x14\x46orwardStatusMessage\x12\x13\n\x06status\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\n\n\x08_message\"Y\n\x15\x42\x61\x63kwardStatusMessage\x12\x13\n\x06status\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\n\n\x08_message2\xf1\x01\n\rWorkerService\x12*\n\x04init\x12\x0e.tensor.Config\x1a\x12.tensor.LogMessage\x12/\n\tset_label\x12\x0e.tensor.Tensor\x1a\x12.tensor.LogMessage\x12?\n\x07\x66orward\x12\x16.tensor.ForwardMessage\x1a\x1c.tensor.ForwardStatusMessage\x12\x42\n\x08\x62\x61\x63kward\x12\x17.tensor.BackwardMessage\x1a\x1d.tensor.BackwardStatusMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker.worker_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORMESSAGE']._serialized_start=69
  _globals['_TENSORMESSAGE']._serialized_end=116
  _globals['_CONFIG']._serialized_start=119
  _globals['_CONFIG']._serialized_end=439
  _globals['_TENSOR']._serialized_start=441
  _globals['_TENSOR']._serialized_end=463
  _globals['_FORWARDMESSAGE']._serialized_start=465
  _globals['_FORWARDMESSAGE']._serialized_end=558
  _globals['_BACKWARDMESSAGE']._serialized_start=560
  _globals['_BACKWARDMESSAGE']._serialized_end=611
  _globals['_LOGMESSAGE']._serialized_start=613
  _globals['_LOGMESSAGE']._serialized_end=677
  _globals['_FORWARDSTATUSMESSAGE']._serialized_start=679
  _globals['_FORWARDSTATUSMESSAGE']._serialized_end=767
  _globals['_BACKWARDSTATUSMESSAGE']._serialized_start=769
  _globals['_BACKWARDSTATUSMESSAGE']._serialized_end=858
  _globals['_WORKERSERVICE']._serialized_start=861
  _globals['_WORKERSERVICE']._serialized_end=1102
# @@protoc_insertion_point(module_scope)
