FROM ubuntu:22.04

# Update package index and upgrade existing packages
RUN apt update -y && \
    apt upgrade -y

# Install Python 3 and pip for package management
RUN apt install -y python3 python3-pip cargo

# RUN apt install protobuf-compiler -y

# # RUN pip3 install fastapi
# RUN pip3 install protobuf
# RUN pip3 install grpcio grpcio-tools
RUN pip3 install kubernetes

# Upgrade numpy
RUN pip3 install --upgrade numpy

ENV PROTOCOL=REST
ENV PARADIGM=centralized