

FROM marcog94/torchslicer:base-cpu-grpc

ENV PARADIGM=centralized
ENV PROTOCOL=GRPC
RUN mkdir /train
COPY examples/train/${PARADIGM}/GRPC/coordinator/ /train/${PARADIGM}/GRPC/coordinator/
COPY examples/train/${PARADIGM}/GRPC/proto_common/ /train/${PARADIGM}/GRPC/proto_common/

WORKDIR /train
RUN cd "${PARADIGM}/${PROTOCOL}" && \
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto_common/coordinator/coordinator_service.proto && \
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto_common/worker/worker_service.proto

#RUN python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. "./${PARADIGM}/${PROTOCOL}/proto_common/coordinator/coordinator_service.proto"
RUN cd /train

CMD python3 "${PARADIGM}/${PROTOCOL}/coordinator/main.py"
