FROM python:3.12.3-slim

# Update package index and upgrade existing packages
RUN apt update -y && \
    apt upgrade -y

# Install Python 3 and pip for package management
RUN apt install -y python3 python3-pip cargo

# Install PyTorch and its dependencies
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu

COPY lib/torchslicer/ /usr/local/bin/torchslicer/
RUN chmod 777 -R /usr/local/bin/torchslicer/*    


RUN python3 -m pip  install /usr/local/bin/torchslicer