FROM ubuntu:22.04

# Update package index and upgrade existing packages
RUN apt update -y && \
    apt upgrade -y

# Install Python 3 and pip for package management
RUN apt install -y python3 python3-pip

# Install PyTorch and its dependencies
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# Upgrade numpy
RUN pip3 install --upgrade numpy

# Set the default command to execute when the container starts
CMD ["python3"]
